<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Fundamentals (Good) Exercises</span></div>

## 2nd attempt: exercise 1 (ignore)

In [ ]:
user_input = input('Please provide me with a number?')
print('You entered', user_input)

Qns: Ask for the name of the user and then print out the greeting:

“How you doin NAME!”

In [1]:
user_input = input('What is your name?')
print(f'How you doin {user_input}')

What is your name? jay


How you doin jay


Ask for the name of the user, then ask for the age of the user and print out the introduction:

“My name is NAME and I am AGE years old.”

In [7]:
name_input = input('What is your name?')
age_input = input('What is your age?')

print(f'My name is {name_input}'+ f' and I am {age_input} years old')

What is your name? jay
What is your age? 15


My name is jay and I am 15 years old


You are given the value of pi as 3.141592653589793

Define the variable pi with this value and then use it to produce the following using f-strings.

- The value of pi to 2 decimal places is: 3.14
- The value of pi to 3 decimal places is: 3.142
- The value of pi to 4 decimal places is: 3.1416

In [17]:
import numpy as np 

x = np.pi

print(f'The value of pi to 2 decimal places is: {x:.2f}')
print(f'The value of pi to 2 decimal places is: {x:.3f}')
print(f'The value of pi to 2 decimal places is: {x:.4f}')

The value of pi to 2 decimal places is: 3.14
The value of pi to 2 decimal places is: 3.142
The value of pi to 2 decimal places is: 3.1416


In [58]:
print(f"{"Apple":10}")

Apple     


In [66]:
## REVISE AGAIN..
print(f"{"Apple":<10} ${0.99}")
print(f"{"Banana":10} ${0.59}")
print(f"{"Orange":10} ${1.29}")

Apple      $0.99
Banana     $0.59
Orange     $1.29


## 2nd attempt: Exercise 2 (ignore)

In [42]:
x = float(input())
print(f"Enter the student's score: {x}")

if 70 <= x <= 100: 
    print('The student letter grade is: A')
elif 50 <= x<= 69:
    print('The student letter grade is: B')
elif 35 <= x <= 49:
    print('The student letter grade is: C')
elif 0 <= x <= 34: 
    print('Fail')
else: 
    print('Error')

 50.5


Enter the student's score: 50.5
The student letter grade is: B


## Exercise 3 (ignore)

In [24]:
def factorial(n):
    if n < 0:
        return "Invalid input"
    elif n == 0:
        return 1
    else:
        result = 1
        for number in range(1, n+1):
            result *= number
        return result


print(factorial(5))   # Testing, expected output: 120
print(factorial(-1))  # Testing, expected output: Invalid input

120
Invalid input


## Exercise 1 (f-strings to the rescue) 

In [ ]:
# Example 1
user_input = input('Please provide me with a number?')
print('You entered', user_input)

In [6]:
# Task 1 
user_input = input('What is your name?') 
print('How you doin', user_input)

What is your name? jay


How you doin jay


In [9]:
# Task 2
user_input_name = input('What is your name?') 
print('My name is', user_input_name)
user_input_age = input('What is your age?') 
print('and I am', user_input_age, 'years old')

What is your name? jay


My name is jay


What is your age? 30


and I am 30 years old


Task 3

You are given the value of pi as 3.141592653589793

Define the variable pi with this value and then use it to produce the following using f-strings.

- The value of pi to 2 decimal places is: 3.14
- The value of pi to 3 decimal places is: 3.142
- The value of pi to 4 decimal places is: 3.1416

In [16]:
import numpy as np
pi = 3.141592653589793
print(f'(The value of pi to 2 decimal places is {np.pi:.2f}')
print(f'(The value of pi to 3 decimal places is {np.pi:.3f}')
print(f'(The value of pi to 4 decimal places is {np.pi:.4f}')

(The value of pi to 2 decimal places is 3.14
(The value of pi to 3 decimal places is 3.142
(The value of pi to 4 decimal places is 3.1416


Task 4 

| Fruit    |  Price   |  
| :--- | :--: | 
| Apple   |  0.99  |  
| Banana  |  0.59  |   
| Orange   |  1.29  |   

In [64]:
fruits_px = [('Apple', 0.99), ('Banana', 0.59), ('Orange', 1.29)] 

for fruit, price in fruits_px: 
    print(f"{fruit:<10} ${price:}")
# how to do this... 

Apple      $0.99
Banana     $0.59
Orange     $1.29


## Exercise 2 (What is your grade?)

| Grade    |  Score Range   |  
| :--- | :--: | 
| A   |  70-100  |  
| B  |  50-69  |   
| C  |  35-49  | 
| D |  0-34 | 

In [67]:
def determine_grade(score): 
    if 70 <= score <= 100: 
        return "A" 
    elif 50 <= score <= 69:
        return "B" 
    elif 35 <= score <= 64:
        return "C" 
    elif 0 <= score <= 34:
        return "D"
    else: 
        return "error" 
        
user_input = input("Enter student's score?")
score = float(user_input)
 
grade = determine_grade(score)

print(f"student's letter grade is: {grade}" )

Enter student's score? 34.5


student's letter grade is: error


In [68]:
x = float(input())
print(f"Enter the student's score: {x}")

if 70 <= x <= 100: 
    print('The student letter grade is: A')
elif 50 <= x<= 69:
    print('The student letter grade is: B')
elif 35 <= x <= 49:
    print('The student letter grade is: C')
elif 0 <= x <= 34: 
    print('Fail')
else: 
    print('Error')

 34.5


Enter the student's score: 34.5
Error


## Exercise 3 (Debugging Code)

In [32]:
def factorial(n):
    if n < 0:
        return "Invalid input"
    elif n == 0:
        return 1
    else:
        result = 1
        for number in range(1, n+1):
            result *= number
        return result


print(factorial(5))   # Testing, expected output: 120
print(factorial(-1))  # Testing, expected output: Invalid input

120
Invalid input
